"use client"

import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"
import { cn } from "@/lib/utils"
import { useState, useEffect } from "react"

const sections = [
  {
    id: "acceptance",
    number: "1",
    title: "Acceptance of Terms",
    paragraphs: [
      'By creating an account, accessing, or using SellerMentor (the "Service"), you acknowledge that you have read, understood, and agree to be bound by these Terms of Service (the "Terms"). These Terms constitute a legally binding agreement between you and SellerMentor.',
      "If you are using the Service on behalf of an organization, you represent and warrant that you have the authority to bind that organization to these Terms. If you do not agree to these Terms, you must not access or use the Service.",
      "We reserve the right to modify these Terms at any time. Material changes will be communicated via email or through a prominent notice within the Service at least thirty (30) days before they take effect. Your continued use of the Service following the effective date of any modifications constitutes acceptance of the revised Terms.",
    ],
  },
  {
    id: "description",
    number: "2",
    title: "Description of Service",
    paragraphs: [
      'SellerMentor is an artificial intelligence platform that assists Amazon sellers in evaluating product opportunities. The Service analyzes publicly available marketplace data, proprietary algorithms, and AI models to generate advisory reports including GO / NO-GO recommendations, profitability estimates, competition analysis, PPC pressure assessments, risk evaluations, differentiation opportunities, dominant brand analysis, break-even calculations, market signals, and review intelligence (collectively, "Analysis Outputs").',
      "The Service is designed to support your decision-making process. It does not replace professional judgment, and all Analysis Outputs are subject to the disclaimers and limitations set forth in these Terms.",
    ],
  },
  {
    id: "ai-disclaimer",
    number: "3",
    title: "AI Output Disclaimer",
    paragraphs: [
      "YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT ALL ANALYSIS OUTPUTS GENERATED BY THE SERVICE ARE ESTIMATES PRODUCED BY ARTIFICIAL INTELLIGENCE MODELS AND MAY CONTAIN INACCURACIES, ERRORS, OR OMISSIONS.",
      "The Service does not guarantee the accuracy, completeness, timeliness, or reliability of any Analysis Output. AI models are probabilistic in nature and may produce different results for the same inputs at different times. Market conditions, competitive landscapes, and platform policies change frequently, and Analysis Outputs may not reflect the most current state of any marketplace.",
      "SellerMentor makes no representation or warranty that any product analyzed through the Service will achieve any particular level of sales, profitability, ranking, or commercial success. Past performance data referenced in Analysis Outputs is not indicative of future results.",
    ],
  },
  {
    id: "not-advice",
    number: "4",
    title: "No Financial, Investment, Legal, or Business Advice",
    paragraphs: [
      "The Service is an informational and analytical tool only. Nothing provided by the Service constitutes:",
      null,
      "All business, investment, and operational decisions remain solely your responsibility. You should consult qualified professionals for financial, legal, tax, and business advice before making any investment or business decisions based on Analysis Outputs.",
    ],
    list: [
      "Financial advice or financial planning recommendations",
      "Investment advice or solicitation to invest in any product or market",
      "Legal advice or legal opinions of any kind",
      "Business guarantees, warranties, or assurances of commercial success",
      "Tax advice or tax planning recommendations",
    ],
  },
  {
    id: "amazon-disclaimer",
    number: "5",
    title: "Amazon Marketplace Disclaimer",
    paragraphs: [
      "SellerMentor is an independent service and is NOT affiliated with, endorsed by, sponsored by, or connected to Amazon.com, Inc. or any of its subsidiaries or affiliates in any way. Amazon, Amazon FBA, Amazon Seller Central, and all related marks are trademarks of Amazon.com, Inc.",
      "The Service does not guarantee any specific ranking, sales volume, or marketplace performance on Amazon or any other platform. Marketplace conditions, algorithms, policies, fee structures, and competitive landscapes are subject to change at any time without notice, and such changes may materially impact the accuracy or relevance of Analysis Outputs.",
      "Amazon seller policies, terms of service, and program requirements may change at any time. It is your sole responsibility to comply with all applicable Amazon policies and terms of service. SellerMentor is not responsible for any policy changes, account suspensions, or other actions taken by Amazon.",
    ],
  },
  {
    id: "third-party-data",
    number: "6",
    title: "Third-Party Data Disclaimer",
    paragraphs: [
      "The Service may incorporate data, estimates, or information derived from third-party sources, including but not limited to marketplace APIs, public datasets, and external data providers. SellerMentor does not control and is not responsible for the accuracy, availability, completeness, or timeliness of any third-party data.",
      "Third-party data sources may experience outages, delays, errors, or discontinuations that may affect the quality or availability of Analysis Outputs. SellerMentor makes no warranty regarding the reliability of third-party data and shall not be liable for any decisions made in reliance upon such data.",
    ],
  },
  {
    id: "accounts",
    number: "7",
    title: "Account Terms",
    paragraphs: [
      "To access the Service, you must create an account and provide accurate, complete, and current information. You are solely responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.",
      "You must notify us immediately at security@amzmentor.ai if you become aware of any unauthorized use of your account or any other breach of security. SellerMentor will not be liable for any loss or damage arising from your failure to protect your account credentials.",
      "We reserve the right to suspend or terminate your account at our sole discretion if we reasonably believe that you have violated these Terms, engaged in fraudulent activity, or used the Service in a manner that could harm SellerMentor, other users, or third parties.",
    ],
  },
  {
    id: "subscriptions",
    number: "8",
    title: "Subscriptions, Billing, and Refunds",
    paragraphs: [
      'Certain features of the Service require a paid subscription ("Paid Plan"). By subscribing to a Paid Plan, you agree to pay the applicable fees as described at the time of purchase. Subscription fees are billed in advance on a recurring basis (monthly or annually, as selected).',
      "You may cancel your subscription at any time through your account settings. Cancellation takes effect at the end of the current billing period, and you will retain access to Paid Plan features until that date. No prorated refunds will be issued for partial billing periods unless required by applicable law.",
      "We reserve the right to modify subscription pricing at any time. Existing subscribers will receive at least thirty (30) days advance notice of any price increase, and the new pricing will apply at the start of the next billing period following the notice period.",
    ],
  },
  {
    id: "ip",
    number: "9",
    title: "Intellectual Property",
    paragraphs: [
      "All content, features, functionality, algorithms, software, designs, text, graphics, and other materials comprising the Service are the exclusive intellectual property of SellerMentor and are protected by copyright, trademark, trade secret, and other intellectual property laws.",
      "Analysis Outputs generated for your account are licensed to you for your personal and internal business use only. You may not resell, redistribute, publicly display, or commercially exploit Analysis Outputs without prior written consent from SellerMentor.",
    ],
  },
  {
    id: "liability",
    number: "10",
    title: "Limitation of Liability",
    paragraphs: [
      'THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.',
      "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL AMZ MENTOR AI, ITS DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO:",
      null,
      "IN NO EVENT SHALL AMZ MENTOR AI'S TOTAL AGGREGATE LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICE EXCEED THE GREATER OF (A) THE AMOUNTS YOU HAVE PAID TO AMZ MENTOR AI IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR (B) ONE HUNDRED U.S. DOLLARS ($100).",
    ],
    list: [
      "Loss of profits, revenue, or anticipated savings",
      "Loss of business or business opportunities",
      "Loss of data or data corruption",
      "Investment losses or financial losses of any kind",
      "Consequential or incidental damages arising from reliance on Analysis Outputs",
      "Damages arising from marketplace policy changes or platform actions",
    ],
  },
  {
    id: "indemnification",
    number: "11",
    title: "Indemnification",
    paragraphs: [
      "You agree to indemnify, defend, and hold harmless SellerMentor, its directors, officers, employees, agents, and affiliates from and against any and all claims, liabilities, damages, losses, costs, and expenses (including reasonable attorneys' fees) arising out of or in connection with:",
      null,
      "This indemnification obligation shall survive the termination of your account and these Terms.",
    ],
    list: [
      "Your use or misuse of the Service",
      "Your violation of these Terms",
      "Your violation of any applicable law, regulation, or third-party right",
      "Any business decisions made based on Analysis Outputs",
      "Any claims by third parties related to your use of the Service",
    ],
  },
  {
    id: "termination",
    number: "12",
    title: "Termination",
    paragraphs: [
      "We may terminate or suspend your account and access to the Service immediately, without prior notice or liability, for any reason, including but not limited to a breach of these Terms. Upon termination, your right to use the Service ceases immediately.",
      "You may terminate your account at any time by contacting us or through your account settings. Termination does not relieve you of any obligations incurred prior to termination, including any outstanding payment obligations.",
      "Sections 3, 4, 5, 6, 10, 11, and 13 shall survive termination of these Terms.",
    ],
  },
  {
    id: "governing",
    number: "13",
    title: "Governing Law and Dispute Resolution",
    paragraphs: [
      "These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law provisions.",
      "Any dispute arising out of or relating to these Terms or the Service shall first be attempted to be resolved through good-faith negotiation. If negotiation fails, the dispute shall be resolved through binding arbitration administered in accordance with the rules of the American Arbitration Association. The arbitration shall be conducted in English.",
      "You agree that any arbitration shall be conducted on an individual basis and not as a class, consolidated, or representative action. You waive any right to participate in a class action lawsuit or class-wide arbitration.",
    ],
  },
  {
    id: "contact",
    number: "14",
    title: "Contact Information",
    paragraphs: [
      "If you have any questions, concerns, or notices regarding these Terms of Service, please contact us:",
    ],
    contact: [
      { label: "General Legal", value: "legal@amzmentor.ai" },
      { label: "Security", value: "security@amzmentor.ai" },
      { label: "Support", value: "support@amzmentor.ai" },
    ],
  },
]

export default function TermsPage() {
  const [activeSection, setActiveSection] = useState("acceptance")

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        const visible = entries.filter((e) => e.isIntersecting)
        if (visible.length > 0) {
          setActiveSection(visible[0].target.id)
        }
      },
      { rootMargin: "-100px 0px -60% 0px", threshold: 0 }
    )

    sections.forEach((s) => {
      const el = document.getElementById(s.id)
      if (el) observer.observe(el)
    })

    return () => observer.disconnect()
  }, [])

  return (
    <div className="relative flex min-h-screen flex-col">
      <div className="pointer-events-none absolute inset-0 bg-gradient-to-br from-[#fef3c7]/60 via-background to-[#dbeafe]/30" />
      <div
        className="pointer-events-none absolute inset-0"
        style={{
          backgroundImage: `radial-gradient(circle at 1px 1px, rgba(0,0,0,0.03) 1px, transparent 0)`,
          backgroundSize: "24px 24px",
        }}
      />
      <Navbar />

      <main className="relative flex-1">
        <div className="mx-auto max-w-[1100px] px-6 py-16 md:py-20">
          {/* Header */}
          <div className="mb-12 max-w-2xl">
            <p className="text-sm font-medium text-primary">Legal</p>
            <h1 className="mt-2 text-3xl font-bold tracking-tight text-foreground md:text-4xl text-balance">
              Terms of Service
            </h1>
            <p className="mt-4 text-base text-muted-foreground leading-relaxed">
              Please read these terms carefully before using SellerMentor. By accessing or using our Service, you agree to be bound by these Terms.
            </p>
            <p className="mt-2 text-sm text-muted-foreground">
              Effective date: February 19, 2026
            </p>
          </div>

          {/* Two-column layout */}
          <div className="flex gap-12">
            {/* Sticky sidebar */}
            <aside className="hidden w-56 shrink-0 lg:block">
              <nav className="sticky top-24">
                <p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground/60 mb-4">
                  On this page
                </p>
                <div className="flex flex-col gap-0.5">
                  {sections.map((s) => (
                    <a
                      key={s.id}
                      href={`#${s.id}`}
                      className={cn(
                        "block rounded-md px-3 py-1.5 text-[13px] leading-snug transition-colors",
                        activeSection === s.id
                          ? "bg-primary/8 font-medium text-primary"
                          : "text-muted-foreground hover:text-foreground hover:bg-secondary/60"
                      )}
                    >
                      {s.number}. {s.title}
                    </a>
                  ))}
                </div>
              </nav>
            </aside>

            {/* Main content */}
            <div className="min-w-0 flex-1">
              <div className="rounded-2xl border border-border bg-card shadow-sm">
                <div className="p-8 md:p-10 lg:p-12">
                  <div className="flex flex-col gap-14">
                    {sections.map((s) => (
                      <section key={s.id} id={s.id} className="scroll-mt-28">
                        <div className="flex items-baseline gap-3 mb-4">
                          <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-primary/8 text-xs font-bold text-primary">
                            {s.number}
                          </span>
                          <h2 className="text-lg font-semibold text-foreground">{s.title}</h2>
                        </div>

                        <div className="flex flex-col gap-4 pl-10">
                          {s.paragraphs.map((p, i) => {
                            if (p === null && s.list) {
                              return (
                                <ul key={i} className="flex flex-col gap-2">
                                  {s.list.map((item, j) => (
                                    <li key={j} className="flex items-start gap-3 text-sm text-muted-foreground leading-relaxed">
                                      <span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-muted-foreground/40" />
                                      {item}
                                    </li>
                                  ))}
                                </ul>
                              )
                            }
                            if (p === null) return null
                            const isUpperCase = p === p.toUpperCase() && p.length > 20
                            return (
                              <p
                                key={i}
                                className={cn(
                                  "text-sm leading-relaxed",
                                  isUpperCase
                                    ? "font-medium text-foreground/90"
                                    : "text-muted-foreground"
                                )}
                              >
                                {p}
                              </p>
                            )
                          })}

                          {s.contact && (
                            <div className="mt-2 rounded-xl border border-border bg-secondary/30 p-5">
                              <div className="flex flex-col gap-3">
                                {s.contact.map((c) => (
                                  <div key={c.label} className="flex items-center justify-between">
                                    <span className="text-sm text-muted-foreground">{c.label}</span>
                                    <span className="text-sm font-medium text-foreground">{c.value}</span>
                                  </div>
                                ))}
                              </div>
                            </div>
                          )}
                        </div>
                      </section>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}
