"use client"

import { useState } from "react"
import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import {
  Megaphone,
  DollarSign,
  Target,
  BarChart3,
  ChevronRight,
  ChevronLeft,
  Check,
  Copy,
  AlertTriangle,
  Zap,
  TrendingUp,
  Calendar,
  ArrowRight,
  Shield,
  Lightbulb,
} from "lucide-react"
import { cn } from "@/lib/utils"

/* ─── Types ─────────────────────────────────────────────── */
type FormData = {
  productName: string
  sellingPrice: string
  fbaFee: string
  cogs: string
  referralPct: number
  monthlyBudget: string
  phase: "launch" | "optimization"
  mainKeyword: string
  additionalKeywords: string
}

type PpcResult = {
  netPerUnit: number
  referralFee: number
  breakEvenAcos: number
  targetAcos: number
  dailyBudget: number
  autoBudget: number
  manualBudget: number
  autoBid: number
  manualBid: number
  keywords: string[]
}

/* ─── Helpers ────────────────────────────────────────────── */
function fmt(n: number, decimals = 2): string {
  return n.toFixed(decimals)
}

function calculateResults(fd: FormData): PpcResult {
  const price = parseFloat(fd.sellingPrice) || 0
  const fba = parseFloat(fd.fbaFee) || 0
  const cogs = parseFloat(fd.cogs) || 0
  const monthly = parseFloat(fd.monthlyBudget) || 0

  const referralFee = price * (fd.referralPct / 100)
  const netPerUnit = price - fba - referralFee - cogs
  const breakEvenAcos = price > 0 ? (netPerUnit / price) * 100 : 0
  const targetAcos = breakEvenAcos * 0.85

  const dailyBudget = monthly / 30
  const autoBudget = dailyBudget * 0.6
  const manualBudget = dailyBudget * 0.4

  const autoBid = price * 0.04
  const manualBid = price * 0.05

  const kws: string[] = []
  if (fd.mainKeyword.trim()) kws.push(fd.mainKeyword.trim())
  if (fd.additionalKeywords.trim()) {
    fd.additionalKeywords
      .split("\n")
      .map((k) => k.trim())
      .filter((k) => k.length > 0)
      .forEach((k) => {
        if (!kws.includes(k)) kws.push(k)
      })
  }

  return {
    netPerUnit,
    referralFee,
    breakEvenAcos,
    targetAcos,
    dailyBudget,
    autoBudget,
    manualBudget,
    autoBid,
    manualBid,
    keywords: kws,
  }
}

const TOTAL_STEPS = 4

const STEP_META = [
  { icon: DollarSign, label: "Your Product" },
  { icon: Target, label: "Your Goals" },
  { icon: Megaphone, label: "Blueprint" },
  { icon: Calendar, label: "Action Plan" },
]

/* ─── Page ───────────────────────────────────────────────── */
export default function PpcWizardPage() {
  const [step, setStep] = useState(1)
  const [copied, setCopied] = useState(false)
  const [formData, setFormData] = useState<FormData>({
    productName: "",
    sellingPrice: "",
    fbaFee: "",
    cogs: "",
    referralPct: 15,
    monthlyBudget: "",
    phase: "launch",
    mainKeyword: "",
    additionalKeywords: "",
  })

  const updateField = <K extends keyof FormData>(field: K, value: FormData[K]) => {
    setFormData((prev) => ({ ...prev, [field]: value }))
  }

  const isStepValid = (): boolean => {
    switch (step) {
      case 1:
        return (
          formData.productName.trim().length > 0 &&
          formData.sellingPrice.trim().length > 0 &&
          parseFloat(formData.sellingPrice) > 0 &&
          formData.fbaFee.trim().length > 0 &&
          formData.cogs.trim().length > 0
        )
      case 2:
        return (
          formData.monthlyBudget.trim().length > 0 &&
          parseFloat(formData.monthlyBudget) > 0 &&
          formData.mainKeyword.trim().length > 0
        )
      case 3:
        return true
      case 4:
        return true
      default:
        return false
    }
  }

  const results: PpcResult = calculateResults(formData)

  const buildCopyText = (): string => {
    const r = results
    const name = formData.productName || "Your Product"
    const kws = r.keywords.join("\n  ")
    return `PPC CAMPAIGN BLUEPRINT — ${name}
Generated by SellerMentor

════════════════════════════════
CAMPAIGN 1 — AUTO DISCOVERY
════════════════════════════════
Campaign name: ${name} — Auto — Launch
Type: Sponsored Products
Targeting: Automatic
Daily budget: $${fmt(r.autoBudget)}
Bid strategy: Dynamic bids — down only
Default bid: $${fmt(r.autoBid)}
Ad group: All Products
Purpose: Discover which search terms convert. Don't touch for 7 days.

════════════════════════════════
CAMPAIGN 2 — MANUAL EXACT
════════════════════════════════
Campaign name: ${name} — Manual Exact — Launch
Type: Sponsored Products
Targeting: Manual — Exact match only
Daily budget: $${fmt(r.manualBudget)}
Bid strategy: Fixed bids
Starting bid per keyword: $${fmt(r.manualBid)}
Ad group: Core Keywords
Keywords:
  ${kws}

════════════════════════════════
YOUR TARGETS
════════════════════════════════
Target ACoS: ${fmt(r.targetAcos)}%
Break-even ACoS: ${fmt(r.breakEvenAcos)}%
Net profit per unit (before ads): $${fmt(r.netPerUnit)}
`
  }

  const handleCopy = () => {
    void navigator.clipboard.writeText(buildCopyText()).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    })
  }

  return (
    <div className="relative flex min-h-screen flex-col">
      <div className="pointer-events-none absolute inset-0 bg-gradient-to-br from-[#fef3c7]/60 via-background to-[#dbeafe]/30" />
      <Navbar />

      <main className="relative flex-1">
        {/* ── Hero ─────────────────────────────────────────── */}
        {step === 1 && (
          <div className="mx-auto max-w-xl px-6 pt-14 pb-4 text-center animate-in fade-in duration-500">
            <div className="mb-4 inline-flex items-center gap-1.5 rounded-full border border-primary/20 bg-primary/5 px-3 py-1 text-xs font-semibold text-primary">
              <Megaphone className="h-3 w-3" />
              PPC Campaign Wizard
            </div>
            <h1 className="text-3xl font-bold tracking-tight text-foreground">
              Build your first Amazon PPC campaign
            </h1>
            <p className="mt-3 text-muted-foreground leading-relaxed">
              Enter your product numbers and get a complete campaign blueprint — exact settings, bids, and a 30-day action plan. No API needed.
            </p>
          </div>
        )}

        <div className="mx-auto w-full max-w-2xl px-6 pb-20 pt-8">
          {/* ── Step indicator ──────────────────────────────── */}
          <div className="mb-6 flex items-center gap-1.5">
            {STEP_META.map((meta, i) => {
              const n = i + 1
              const Icon = meta.icon
              const active = n === step
              const done = n < step
              return (
                <div key={n} className="flex items-center gap-1.5">
                  <div
                    className={cn(
                      "flex h-7 w-7 items-center justify-center rounded-full border text-xs font-semibold transition-all duration-300",
                      done && "border-primary bg-primary text-primary-foreground",
                      active && "border-primary bg-primary/10 text-primary",
                      !done && !active && "border-border bg-card text-muted-foreground"
                    )}
                  >
                    {done ? <Check className="h-3.5 w-3.5" /> : <Icon className="h-3.5 w-3.5" />}
                  </div>
                  <span
                    className={cn(
                      "hidden text-xs font-medium sm:inline",
                      active ? "text-foreground" : "text-muted-foreground"
                    )}
                  >
                    {meta.label}
                  </span>
                  {i < STEP_META.length - 1 && (
                    <div
                      className={cn(
                        "h-px flex-1 w-6 transition-colors duration-300",
                        done ? "bg-primary" : "bg-border"
                      )}
                    />
                  )}
                </div>
              )
            })}
          </div>

          {/* ── Progress bar ────────────────────────────────── */}
          <div className="mb-2 flex items-center justify-between">
            <span className="text-xs font-medium text-muted-foreground">
              Step {step} of {TOTAL_STEPS}
            </span>
            <span className="text-xs font-medium text-muted-foreground">
              {Math.round((step / TOTAL_STEPS) * 100)}%
            </span>
          </div>
          <div className="mb-10 h-1 w-full overflow-hidden rounded-full bg-secondary">
            <div
              className="h-full rounded-full bg-primary transition-all duration-500 ease-out"
              style={{ width: `${(step / TOTAL_STEPS) * 100}%` }}
            />
          </div>

          {/* ── Step Content ────────────────────────────────── */}
          <div className="min-h-[320px]">

            {/* STEP 1 ─────────────────────────────────────── */}
            {step === 1 && (
              <div className="animate-in fade-in slide-in-from-right-4 duration-300">
                <h2 className="text-2xl font-bold text-foreground mb-2">
                  Tell us about your product
                </h2>
                <p className="text-muted-foreground mb-8 leading-relaxed">
                  We&apos;ll calculate your break-even and build your campaign around real numbers.
                </p>

                <div className="flex flex-col gap-5">
                  {/* Product name */}
                  <div className="flex flex-col gap-1.5">
                    <label className="text-sm font-semibold text-foreground">Product name</label>
                    <Input
                      placeholder="e.g. Bamboo Cutting Board with Juice Groove"
                      value={formData.productName}
                      onChange={(e) => updateField("productName", e.target.value)}
                      className="h-12 rounded-xl border-border bg-card text-base placeholder:text-muted-foreground/50 focus-visible:ring-primary/30"
                      autoFocus
                    />
                  </div>

                  {/* Selling price */}
                  <div className="flex flex-col gap-1.5">
                    <label className="text-sm font-semibold text-foreground">Selling price</label>
                    <div className="relative max-w-xs">
                      <span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-sm text-muted-foreground">$</span>
                      <Input
                        type="number"
                        min="0"
                        step="0.01"
                        placeholder="e.g. 34.99"
                        value={formData.sellingPrice}
                        onChange={(e) => updateField("sellingPrice", e.target.value)}
                        className="h-12 rounded-xl border-border bg-card pl-7 text-base placeholder:text-muted-foreground/50 focus-visible:ring-primary/30"
                      />
                    </div>
                  </div>

                  {/* FBA fee */}
                  <div className="flex flex-col gap-1.5">
                    <label className="text-sm font-semibold text-foreground">FBA fee</label>
                    <div className="relative max-w-xs">
                      <span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-sm text-muted-foreground">$</span>
                      <Input
                        type="number"
                        min="0"
                        step="0.01"
                        placeholder="e.g. 5.40"
                        value={formData.fbaFee}
                        onChange={(e) => updateField("fbaFee", e.target.value)}
                        className="h-12 rounded-xl border-border bg-card pl-7 text-base placeholder:text-muted-foreground/50 focus-visible:ring-primary/30"
                      />
                    </div>
                    <p className="text-xs text-muted-foreground flex items-center gap-1">
                      <Lightbulb className="h-3 w-3 text-amber-500" />
                      Find this in Amazon&apos;s FBA Revenue Calculator (free)
                    </p>
                  </div>

                  {/* COGS */}
                  <div className="flex flex-col gap-1.5">
                    <label className="text-sm font-semibold text-foreground">
                      Cost of goods + shipping to Amazon
                    </label>
                    <div className="relative max-w-xs">
                      <span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-sm text-muted-foreground">$</span>
                      <Input
                        type="number"
                        min="0"
                        step="0.01"
                        placeholder="e.g. 8.00"
                        value={formData.cogs}
                        onChange={(e) => updateField("cogs", e.target.value)}
                        className="h-12 rounded-xl border-border bg-card pl-7 text-base placeholder:text-muted-foreground/50 focus-visible:ring-primary/30"
                      />
                    </div>
                    <p className="text-xs text-muted-foreground flex items-center gap-1">
                      <Lightbulb className="h-3 w-3 text-amber-500" />
                      Your landed cost per unit
                    </p>
                  </div>

                  {/* Referral % */}
                  <div className="flex flex-col gap-1.5">
                    <label className="text-sm font-semibold text-foreground">
                      Amazon referral fee
                    </label>
                    <div className="flex flex-col gap-2 max-w-sm">
                      {[
                        { pct: 15, label: "15% — Most categories" },
                        { pct: 8, label: "8% — Electronics" },
                        { pct: 17, label: "17% — Clothing" },
                        { pct: 20, label: "20% — Jewelry" },
                      ].map((opt) => (
                        <button
                          key={opt.pct}
                          type="button"
                          onClick={() => updateField("referralPct", opt.pct)}
                          className={cn(
                            "flex items-center gap-3 rounded-xl border-2 px-4 py-2.5 text-left transition-all",
                            formData.referralPct === opt.pct
                              ? "border-primary bg-primary/5"
                              : "border-border bg-card hover:border-primary/30"
                          )}
                        >
                          <div
                            className={cn(
                              "flex h-4 w-4 shrink-0 items-center justify-center rounded-full border-2 transition-all",
                              formData.referralPct === opt.pct ? "border-primary" : "border-border"
                            )}
                          >
                            {formData.referralPct === opt.pct && (
                              <div className="h-2 w-2 rounded-full bg-primary" />
                            )}
                          </div>
                          <span className="text-sm font-medium text-foreground">{opt.label}</span>
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* STEP 2 ─────────────────────────────────────── */}
            {step === 2 && (
              <div className="animate-in fade-in slide-in-from-right-4 duration-300">
                <h2 className="text-2xl font-bold text-foreground mb-2">
                  What do you want from PPC?
                </h2>
                <p className="text-muted-foreground mb-6 leading-relaxed">
                  Be realistic. Most new sellers lose money on ads in month 1 — that&apos;s expected. The goal is data, not profit.
                </p>

                {/* Calculated metrics */}
                <div className="mb-8 grid grid-cols-3 gap-3 rounded-2xl border border-border bg-card p-4">
                  <div className="flex flex-col gap-1 text-center">
                    <span className="text-xs font-medium text-muted-foreground leading-tight">Net profit/unit (before ads)</span>
                    <span
                      className={cn(
                        "text-xl font-bold tabular-nums",
                        results.netPerUnit >= 0 ? "text-emerald-600" : "text-destructive"
                      )}
                    >
                      ${fmt(results.netPerUnit)}
                    </span>
                  </div>
                  <div className="flex flex-col gap-1 text-center border-x border-border px-2">
                    <span className="text-xs font-medium text-muted-foreground leading-tight">Break-even ACoS</span>
                    <span className="text-xl font-bold tabular-nums text-foreground">
                      {fmt(results.breakEvenAcos)}%
                    </span>
                  </div>
                  <div className="flex flex-col gap-1 text-center">
                    <span className="text-xs font-medium text-muted-foreground leading-tight">Target ACoS (launch)</span>
                    <span className="text-xl font-bold tabular-nums text-primary">
                      {fmt(results.targetAcos)}%
                    </span>
                  </div>
                </div>

                <div className="flex flex-col gap-5">
                  {/* Monthly budget */}
                  <div className="flex flex-col gap-1.5">
                    <label className="text-sm font-semibold text-foreground">Monthly PPC budget</label>
                    <div className="relative max-w-xs">
                      <span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-sm text-muted-foreground">$</span>
                      <Input
                        type="number"
                        min="0"
                        step="1"
                        placeholder="e.g. 600"
                        value={formData.monthlyBudget}
                        onChange={(e) => updateField("monthlyBudget", e.target.value)}
                        className="h-12 rounded-xl border-border bg-card pl-7 text-base placeholder:text-muted-foreground/50 focus-visible:ring-primary/30"
                        autoFocus
                      />
                    </div>
                    <p className="text-xs text-muted-foreground flex items-center gap-1">
                      <Lightbulb className="h-3 w-3 text-amber-500" />
                      We recommend minimum $20/day ($600/month) for meaningful data in 30 days
                    </p>
                  </div>

                  {/* Phase */}
                  <div className="flex flex-col gap-1.5">
                    <label className="text-sm font-semibold text-foreground">Launch phase or optimization phase?</label>
                    <div className="flex flex-col gap-2">
                      {[
                        {
                          value: "launch" as const,
                          label: "Launch phase (first 60 days)",
                          desc: "Priority: rank and reviews. Accept higher ACoS.",
                        },
                        {
                          value: "optimization" as const,
                          label: "Optimization phase (60+ days)",
                          desc: "Priority: profitability. Tighten ACoS to target.",
                        },
                      ].map((opt) => (
                        <button
                          key={opt.value}
                          type="button"
                          onClick={() => updateField("phase", opt.value)}
                          className={cn(
                            "flex items-start gap-3 rounded-xl border-2 p-4 text-left transition-all",
                            formData.phase === opt.value
                              ? "border-primary bg-primary/5"
                              : "border-border bg-card hover:border-primary/30"
                          )}
                        >
                          <div
                            className={cn(
                              "mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full border-2 transition-all",
                              formData.phase === opt.value ? "border-primary" : "border-border"
                            )}
                          >
                            {formData.phase === opt.value && (
                              <div className="h-2.5 w-2.5 rounded-full bg-primary" />
                            )}
                          </div>
                          <div>
                            <span className="text-sm font-semibold text-foreground">{opt.label}</span>
                            <p className="mt-0.5 text-xs text-muted-foreground">{opt.desc}</p>
                          </div>
                        </button>
                      ))}
                    </div>
                  </div>

                  {/* Main keyword */}
                  <div className="flex flex-col gap-1.5">
                    <label className="text-sm font-semibold text-foreground">Main keyword</label>
                    <Input
                      placeholder="e.g. bamboo cutting board"
                      value={formData.mainKeyword}
                      onChange={(e) => updateField("mainKeyword", e.target.value)}
                      className="h-12 rounded-xl border-border bg-card text-base placeholder:text-muted-foreground/50 focus-visible:ring-primary/30"
                    />
                    <p className="text-xs text-muted-foreground flex items-center gap-1">
                      <Lightbulb className="h-3 w-3 text-amber-500" />
                      Your single most important keyword — the one you want to rank for most
                    </p>
                  </div>

                  {/* Additional keywords */}
                  <div className="flex flex-col gap-1.5">
                    <label className="text-sm font-semibold text-foreground">
                      3–5 additional keywords
                    </label>
                    <Textarea
                      placeholder={"e.g.\nwood cutting board kitchen\nlarge cutting board with juice groove\nbamboo chopping board"}
                      value={formData.additionalKeywords}
                      onChange={(e) => updateField("additionalKeywords", e.target.value)}
                      rows={4}
                      className="resize-none rounded-xl border-border bg-card text-base leading-relaxed placeholder:text-muted-foreground/50 focus-visible:ring-primary/30 p-4"
                    />
                    <p className="text-xs text-muted-foreground flex items-center gap-1">
                      <Lightbulb className="h-3 w-3 text-amber-500" />
                      One keyword per line
                    </p>
                  </div>
                </div>
              </div>
            )}

            {/* STEP 3 — Blueprint Output ─────────────────── */}
            {step === 3 && (
              <div className="animate-in fade-in slide-in-from-right-4 duration-300">
                <div className="mb-1 flex items-center justify-between gap-4">
                  <div>
                    <h2 className="text-2xl font-bold text-foreground">
                      Your PPC Campaign Blueprint
                    </h2>
                    <p className="mt-1 text-muted-foreground leading-relaxed">
                      Two campaigns. Copy these settings exactly into Amazon Seller Central.
                    </p>
                  </div>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={handleCopy}
                    className="shrink-0 gap-1.5 rounded-xl"
                  >
                    {copied ? (
                      <>
                        <Check className="h-3.5 w-3.5 text-emerald-500" />
                        Copied!
                      </>
                    ) : (
                      <>
                        <Copy className="h-3.5 w-3.5" />
                        Copy all
                      </>
                    )}
                  </Button>
                </div>

                {/* ACoS targets summary */}
                <div className="my-6 flex flex-wrap items-center gap-3 rounded-2xl border border-primary/20 bg-primary/5 px-5 py-4">
                  <div className="flex items-center gap-1.5">
                    <Target className="h-4 w-4 text-primary" />
                    <span className="text-sm font-semibold text-foreground">
                      Target ACoS: {fmt(results.targetAcos)}%
                    </span>
                  </div>
                  <span className="text-muted-foreground/40">|</span>
                  <span className="text-sm text-muted-foreground">
                    Break-even: {fmt(results.breakEvenAcos)}%
                  </span>
                  <span className="text-muted-foreground/40">|</span>
                  <span className="text-sm text-muted-foreground">
                    Buffer:{" "}
                    <span className="font-semibold text-emerald-600">
                      {fmt(results.breakEvenAcos - results.targetAcos)}% margin
                    </span>
                  </span>
                </div>

                {/* Campaign 1 — Auto */}
                <div className="mb-4 overflow-hidden rounded-2xl border border-amber-200/60 bg-card shadow-sm">
                  <div className="flex items-center gap-2.5 border-b border-amber-200/60 bg-amber-50/60 px-5 py-3.5 dark:bg-amber-950/20">
                    <Zap className="h-4 w-4 text-amber-600" />
                    <span className="text-sm font-bold text-amber-700 dark:text-amber-400">
                      Campaign 1 — Auto Discovery Campaign
                    </span>
                  </div>
                  <div className="p-5">
                    <dl className="grid grid-cols-1 gap-2.5 sm:grid-cols-2">
                      {[
                        {
                          label: "Campaign name",
                          value: `${formData.productName || "Your Product"} — Auto — Launch`,
                          full: true,
                        },
                        { label: "Type", value: "Sponsored Products" },
                        { label: "Targeting", value: "Automatic" },
                        { label: "Daily budget", value: `$${fmt(results.autoBudget)}` },
                        { label: "Bid strategy", value: "Dynamic bids — down only" },
                        { label: "Default bid", value: `$${fmt(results.autoBid)}` },
                        { label: "Ad group", value: "All Products" },
                      ].map((row) => (
                        <div
                          key={row.label}
                          className={cn(
                            "flex flex-col gap-0.5",
                            row.full && "sm:col-span-2"
                          )}
                        >
                          <dt className="text-xs font-medium text-muted-foreground">{row.label}</dt>
                          <dd className="text-sm font-semibold text-foreground">{row.value}</dd>
                        </div>
                      ))}
                    </dl>
                    <div className="mt-4 flex items-start gap-2 rounded-xl bg-amber-50/80 px-3.5 py-3 dark:bg-amber-950/30">
                      <Lightbulb className="mt-0.5 h-3.5 w-3.5 shrink-0 text-amber-600" />
                      <p className="text-xs text-amber-800 dark:text-amber-300">
                        <strong>Purpose:</strong> Discover which search terms convert. Don&apos;t touch for 7 days.
                      </p>
                    </div>
                  </div>
                </div>

                {/* Campaign 2 — Manual */}
                <div className="mb-4 overflow-hidden rounded-2xl border border-primary/20 bg-card shadow-sm">
                  <div className="flex items-center gap-2.5 border-b border-primary/20 bg-primary/5 px-5 py-3.5">
                    <Target className="h-4 w-4 text-primary" />
                    <span className="text-sm font-bold text-primary">
                      Campaign 2 — Manual Exact — Core Keywords
                    </span>
                  </div>
                  <div className="p-5">
                    <dl className="grid grid-cols-1 gap-2.5 sm:grid-cols-2">
                      {[
                        {
                          label: "Campaign name",
                          value: `${formData.productName || "Your Product"} — Manual Exact — Launch`,
                          full: true,
                        },
                        { label: "Type", value: "Sponsored Products" },
                        { label: "Targeting", value: "Manual — Exact match only" },
                        { label: "Daily budget", value: `$${fmt(results.manualBudget)}` },
                        { label: "Bid strategy", value: "Fixed bids" },
                        { label: "Starting bid per keyword", value: `$${fmt(results.manualBid)}` },
                        { label: "Ad group", value: "Core Keywords" },
                      ].map((row) => (
                        <div
                          key={row.label}
                          className={cn(
                            "flex flex-col gap-0.5",
                            row.full && "sm:col-span-2"
                          )}
                        >
                          <dt className="text-xs font-medium text-muted-foreground">{row.label}</dt>
                          <dd className="text-sm font-semibold text-foreground">{row.value}</dd>
                        </div>
                      ))}
                      <div className="flex flex-col gap-1 sm:col-span-2">
                        <dt className="text-xs font-medium text-muted-foreground">Keywords</dt>
                        <dd className="rounded-lg border border-border bg-secondary/30 p-3">
                          {results.keywords.length > 0 ? (
                            <ul className="flex flex-col gap-1">
                              {results.keywords.map((kw) => (
                                <li key={kw} className="flex items-center gap-1.5 text-sm font-medium text-foreground">
                                  <span className="h-1 w-1 rounded-full bg-primary" />
                                  {kw}
                                </li>
                              ))}
                            </ul>
                          ) : (
                            <span className="text-sm text-muted-foreground italic">
                              Add keywords in Step 2
                            </span>
                          )}
                        </dd>
                      </div>
                    </dl>
                    <div className="mt-4 flex items-start gap-2 rounded-xl bg-primary/5 px-3.5 py-3">
                      <Lightbulb className="mt-0.5 h-3.5 w-3.5 shrink-0 text-primary" />
                      <p className="text-xs text-primary/90">
                        <strong>Purpose:</strong> Aggressive push on your best keywords from day 1.
                      </p>
                    </div>
                  </div>
                </div>

                {/* Week 1 Rule callout */}
                <div className="rounded-2xl border border-destructive/20 bg-destructive/5 p-4">
                  <div className="flex items-start gap-3">
                    <Shield className="mt-0.5 h-5 w-5 shrink-0 text-destructive" />
                    <div>
                      <p className="text-sm font-bold text-destructive">Week 1 Rule — Read This</p>
                      <p className="mt-1 text-sm text-muted-foreground leading-relaxed">
                        Do <strong>NOT</strong> touch either campaign for the first 7 days. Amazon&apos;s algorithm needs time to learn. Pausing or changing bids in week 1 resets the learning phase and wastes your data.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* STEP 4 — 30-Day Action Plan ───────────────── */}
            {step === 4 && (
              <div className="animate-in fade-in slide-in-from-right-4 duration-300">
                <h2 className="text-2xl font-bold text-foreground mb-2">
                  Your Week-by-Week Playbook
                </h2>
                <p className="text-muted-foreground mb-8 leading-relaxed">
                  Follow this exactly. Most new sellers fail by checking campaigns too often and changing settings too fast.
                </p>

                {/* Week cards */}
                <div className="flex flex-col gap-4">

                  {/* Week 1 */}
                  <div className="overflow-hidden rounded-2xl border border-border bg-card">
                    <div className="flex items-center gap-2.5 border-b border-border bg-secondary/40 px-5 py-3.5">
                      <div className="flex h-6 w-6 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">
                        1
                      </div>
                      <span className="text-sm font-bold text-foreground">Week 1 (Days 1–7): Let It Run</span>
                    </div>
                    <div className="p-5">
                      <div className="grid gap-4 sm:grid-cols-2">
                        <div>
                          <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-emerald-600">DO</p>
                          <ul className="flex flex-col gap-2">
                            {[
                              "Check total spend daily — make sure budget isn't exhausted by noon",
                              "Monitor if BSR is moving (lower number = more sales)",
                            ].map((item) => (
                              <li key={item} className="flex items-start gap-2 text-sm text-foreground">
                                <Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-emerald-500" />
                                {item}
                              </li>
                            ))}
                          </ul>
                        </div>
                        <div>
                          <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-destructive">DO NOT</p>
                          <ul className="flex flex-col gap-2">
                            {[
                              "Change any bids or budgets",
                              "Pause campaigns even if ACoS looks high",
                            ].map((item) => (
                              <li key={item} className="flex items-start gap-2 text-sm text-foreground">
                                <AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0 text-destructive" />
                                {item}
                              </li>
                            ))}
                          </ul>
                        </div>
                      </div>
                      <div className="mt-4 flex items-center gap-2 rounded-xl bg-secondary/40 px-3.5 py-2.5">
                        <BarChart3 className="h-3.5 w-3.5 text-primary" />
                        <p className="text-xs font-medium text-foreground">
                          Goal metric: <strong>Impressions &gt; 1,000/day</strong> — if not, bids may be too low
                        </p>
                      </div>
                    </div>
                  </div>

                  {/* Week 2 */}
                  <div className="overflow-hidden rounded-2xl border border-border bg-card">
                    <div className="flex items-center gap-2.5 border-b border-border bg-secondary/40 px-5 py-3.5">
                      <div className="flex h-6 w-6 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">
                        2
                      </div>
                      <span className="text-sm font-bold text-foreground">Week 2 (Days 8–14): First Optimization</span>
                    </div>
                    <div className="p-5">
                      <ul className="flex flex-col gap-3">
                        {[
                          "Download Search Term Report (Campaign Manager → Reports → Scheduled Reports → Search Term)",
                          "Find search terms with 10+ clicks and 0 orders → add as Negative Exact to auto campaign",
                          "Find search terms with 3+ orders at good ACoS → add to Manual Exact with 20% higher bid",
                          "Review: Is manual campaign spending its full budget? If not, raise bids by 20%",
                        ].map((item) => (
                          <li key={item} className="flex items-start gap-2.5 text-sm text-foreground">
                            <ChevronRight className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
                            {item}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>

                  {/* Week 3 */}
                  <div className="overflow-hidden rounded-2xl border border-border bg-card">
                    <div className="flex items-center gap-2.5 border-b border-border bg-secondary/40 px-5 py-3.5">
                      <div className="flex h-6 w-6 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">
                        3
                      </div>
                      <span className="text-sm font-bold text-foreground">Week 3 (Days 15–21): Scale What Works</span>
                    </div>
                    <div className="p-5">
                      <ul className="flex flex-col gap-3">
                        {[
                          "Identify your top 3 converting search terms — these are your ranking keywords",
                          "Create Campaign 3: Manual Exact — Rank Push (budget: $10/day, higher bids on top 3 only)",
                          "Pause any auto keywords that have 20+ clicks, 0 orders, and you've added as negatives",
                          "Check your organic rank for main keyword — are you in top 30? Top 20?",
                        ].map((item) => (
                          <li key={item} className="flex items-start gap-2.5 text-sm text-foreground">
                            <TrendingUp className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
                            {item}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>

                  {/* Week 4 */}
                  <div className="overflow-hidden rounded-2xl border border-border bg-card">
                    <div className="flex items-center gap-2.5 border-b border-border bg-secondary/40 px-5 py-3.5">
                      <div className="flex h-6 w-6 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">
                        4
                      </div>
                      <span className="text-sm font-bold text-foreground">Week 4 (Days 22–30): Decide and Report</span>
                    </div>
                    <div className="p-5">
                      <ul className="flex flex-col gap-3">
                        {[
                          "Calculate actual ACoS: total spend ÷ total ad revenue × 100",
                          `Compare to your target ACoS: ${fmt(results.targetAcos)}%`,
                          "If actual > target by more than 10%: reduce bids by 15% across all campaigns",
                          "If actual < target: increase budgets by 20% — you're leaving profitable sales on the table",
                          "Calculate total revenue, ad spend, and net profit for the month",
                        ].map((item) => (
                          <li key={item} className="flex items-start gap-2.5 text-sm text-foreground">
                            <BarChart3 className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
                            {item}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>

                  {/* Month 1 Checklist */}
                  <div className="overflow-hidden rounded-2xl border border-primary/20 bg-primary/5">
                    <div className="flex items-center gap-2.5 border-b border-primary/20 px-5 py-3.5">
                      <Check className="h-4 w-4 text-primary" />
                      <span className="text-sm font-bold text-primary">Month 1 Summary Checklist</span>
                    </div>
                    <div className="p-5">
                      <ul className="flex flex-col gap-2.5">
                        {[
                          "Downloaded Search Term Report",
                          "Added negative keywords",
                          "Created Manual Exact campaign from auto winners",
                          "Calculated actual ACoS",
                          "Know your top 3 ranking keywords",
                        ].map((item) => (
                          <li key={item} className="flex items-center gap-2.5 text-sm text-foreground">
                            <div className="flex h-4 w-4 shrink-0 items-center justify-center rounded border border-border bg-card">
                            </div>
                            {item}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>

                  {/* CTA */}
                  <div className="rounded-2xl border border-border bg-card p-6 text-center">
                    <div className="mb-2 flex items-center justify-center gap-2">
                      <Shield className="h-5 w-5 text-primary" />
                      <h3 className="text-base font-bold text-foreground">
                        Before you spend on ads — know your product is worth launching
                      </h3>
                    </div>
                    <p className="mb-5 text-sm text-muted-foreground">
                      Run a full profitability and competition analysis before committing ad budget. It takes 30 seconds.
                    </p>
                    <Button asChild className="gap-2 rounded-xl px-6 h-11">
                      <a href="/analyze">
                        Run Product Analysis
                        <ArrowRight className="h-4 w-4" />
                      </a>
                    </Button>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* ── Navigation ──────────────────────────────────── */}
          <div className="mt-10 flex items-center justify-between">
            <Button
              variant="ghost"
              onClick={() => setStep(step - 1)}
              disabled={step === 1}
              className="gap-2 text-muted-foreground hover:text-foreground"
            >
              <ChevronLeft className="h-4 w-4" />
              Back
            </Button>
            {step < TOTAL_STEPS ? (
              <Button
                onClick={() => setStep(step + 1)}
                disabled={!isStepValid()}
                className="gap-2 rounded-xl px-8 h-11"
                title={!isStepValid() ? "Complete all required fields to continue" : undefined}
              >
                {step === 2 ? "Build my blueprint" : "Continue"}
                <ChevronRight className="h-4 w-4" />
              </Button>
            ) : (
              <Button
                onClick={() => {
                  setStep(1)
                  setFormData({
                    productName: "",
                    sellingPrice: "",
                    fbaFee: "",
                    cogs: "",
                    referralPct: 15,
                    monthlyBudget: "",
                    phase: "launch",
                    mainKeyword: "",
                    additionalKeywords: "",
                  })
                }}
                variant="outline"
                className="gap-2 rounded-xl px-6 h-11"
              >
                Start over
                <ChevronRight className="h-4 w-4" />
              </Button>
            )}
          </div>
        </div>
      </main>

      <div className="relative z-10 bg-background">
        <Footer />
      </div>
    </div>
  )
}
